export interface ConfirmacionMensaje {
    msjTipo: number;
    titulo:  String;
    mensaje: String;
    detalle: String;
  }


export interface bcCliente {
    msjTipo: String;
    titulo:  String;
    mensaje: String;
    detalle: String;
  }

  // Generated by https://quicktype.io
export interface listados {
  id:          Number;
  descripcion: String;
}

